CREATE DATABASE AMYCO_V1_1;
USE AMYCO_V1_1;


--## table dblinks ##
CREATE TABLE IF NOT EXISTS DBLINKS( 
	DATAB_ID INT NOT NULL,
	ABBREVIATION VARCHAR(100) NOT NULL UNIQUE,
	WEBLINK VARCHAR(500) NOT NULL, 
	PRIMARY KEY(DATAB_ID));


--## table disease ##
CREATE TABLE IF NOT EXISTS DISEASE( 
	DISEASE_ID INT NOT NULL,
	DISEASE_NAME LONGTEXT,
    DISEASE_DESCRIPTION LONGTEXT,
	DISEASE_TYPE VARCHAR(300),
    DISEASE_ASSOCIATION VARCHAR(300),
	DISEASE_TISSUE TEXT,
	DISEASE_ISA_NAME TEXT,
	PRIMARY KEY(DISEASE_ID) );
		
ALTER TABLE DISEASE CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;    

		
--## table protein ##
CREATE TABLE IF NOT EXISTS PROTEIN(
    PROTEIN_ID INT NOT NULL,
	AC VARCHAR(20) NOT NULL UNIQUE,
    UNIPROT_ID VARCHAR(100),
    PRIMARY_NAME TEXT NOT NULL,
    SIPE_NAME TEXT NOT NULL,
	PROTEIN_NAMES TEXT NOT NULL,
    SEQ_LENGTH INT NOT NULL,
    GENENAME TEXT,
    SEQUENCE LONGTEXT NOT NULL,
	FUNCTION_ LONGTEXT,
    PRIMARY KEY(PROTEIN_ID)) ;
    
ALTER TABLE PROTEIN CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
	
    --## table PROTEIN2disease ##
CREATE TABLE IF NOT EXISTS PROTEIN_TO_DISEASE(
    ID INT NOT NULL,
	DIS_ID INT NOT NULL,
    PR_ID INT NOT NULL,
    RELATIONSHIP VARCHAR(100),
    PUBMED_ID VARCHAR(100),
    AMYPRO_ID VARCHAR(100),
    FOREIGN KEY(PR_ID)  REFERENCES PROTEIN(PROTEIN_ID), 
    FOREIGN KEY(DIS_ID)  REFERENCES DISEASE(DISEASE_ID), 
    PRIMARY KEY(ID)) ;
    
    
--## table alternative_names ##
CREATE TABLE IF NOT EXISTS ALTERNATIVE_NAMES(
    ID INT NOT NULL,
	DIS_ID INT NOT NULL,
	ALTERNATIVE_NAME LONGTEXT,
    FOREIGN KEY(DIS_ID)  REFERENCES DISEASE(DISEASE_ID), 
    PRIMARY KEY(ID)) ;
	
ALTER TABLE ALTERNATIVE_NAMES CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  

    
--## table CROSSREFERENCES ##
CREATE TABLE IF NOT EXISTS CROSSREFERENCES(
    ID INT NOT NULL,
	DIS_ID INT NOT NULL,
    CROSSREF_ID VARCHAR(100) NOT NULL,
    DATAB_ID INT NOT NULL,
    FOREIGN KEY(DIS_ID)  REFERENCES DISEASE(DISEASE_ID), 
    FOREIGN KEY(DATAB_ID)  REFERENCES DBLINKS(DATAB_ID), 
    PRIMARY KEY(ID)) ;
	
--## table disease_mappings ##
CREATE TABLE IF NOT EXISTS DISEASE_MAPPINGS(
    ID INT NOT NULL,
	DIS_FROM_ID INT NOT NULL,
	DIS_TO_ID INT NOT NULL,
    FOREIGN KEY(DIS_FROM_ID)  REFERENCES DISEASE(DISEASE_ID), 
	FOREIGN KEY(DIS_TO_ID)  REFERENCES DISEASE(DISEASE_ID), 
    PRIMARY KEY(ID)) ;
    
	
show TABLES;
--ALTER TABLE tablename CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci; 

INSERT INTO DISEASE VALUES(72, 'Hypotrichosis Simplex of the Scalp', '', 'Amyloidosis', 'Diseases of the Skin and Subcutaneous Tissue', 'Skin', '');

INSERT INTO DISEASE VALUES(73, 'Senile Seminal Vesicle Amyloidosis', '', 'Amyloidosis', 'Amyloidosis', 'Seminal Vesicle, Deferent Duct, Ejaculatory Duct', '');

INSERT INTO DISEASE VALUES(74, 'Pick Disease of the Brain', 'A rare form of dementia that is sometimes familial. Clinical features include aphasia; apraxia; confusion; anomia; memory loss; and personality deterioration. This pattern is consistent with the pathologic findings of circumscribed atrophy of the poles of the frontal lobe and temporal lobe. Neuronal loss is maximal in the hippocampus, entorhinal cortex, and amygdala. Some ballooned cortical neurons contain argentophylic (Pick) bodies.', 'Amyloidosis', 'Diseases of the Nervous System', 'Central Nervous System (CNS)', '');


INSERT INTO ALTERNATIVE_NAMES VALUES(694, 72, "Hereditary hypotrichosis simplex of the scalp");
INSERT INTO ALTERNATIVE_NAMES VALUES(695, 72, "Hypotrichosis 2");
INSERT INTO ALTERNATIVE_NAMES VALUES(696, 72, "HYPT2");
INSERT INTO ALTERNATIVE_NAMES VALUES(697, 72, "Hypotrichosis simplex of the scalp 1");
INSERT INTO ALTERNATIVE_NAMES VALUES(698, 72, "HTSS1");
INSERT INTO ALTERNATIVE_NAMES VALUES(699, 72, "HTSS");
INSERT INTO ALTERNATIVE_NAMES VALUES(700, 72, "HSS");
INSERT INTO ALTERNATIVE_NAMES VALUES(701, 72, "Hypotrichosis, Spanish Type");
INSERT INTO ALTERNATIVE_NAMES VALUES(702, 73, "SSVA");
INSERT INTO ALTERNATIVE_NAMES VALUES(703, 73, "Senile Seminal Tract Amyloidosis");
INSERT INTO ALTERNATIVE_NAMES VALUES(704, 73, "SSTA");
INSERT INTO ALTERNATIVE_NAMES VALUES(705, 73, "Ejaculatory duct amyloidosis");
INSERT INTO ALTERNATIVE_NAMES VALUES(706, 73, "Spermatic duct amyloidosis");
INSERT INTO ALTERNATIVE_NAMES VALUES(707, 74, "Brain Atrophy, Circumscribed Lobar");
INSERT INTO ALTERNATIVE_NAMES VALUES(708, 74, "Circumscribed Lobar Atrophy of the Brain");
INSERT INTO ALTERNATIVE_NAMES VALUES(709, 74, "Dementia with Lobar Atrophy and Neuronal Cytoplasmic Inclusions");
INSERT INTO ALTERNATIVE_NAMES VALUES(710, 74, "Lobar Atrophy (Brain)");
INSERT INTO ALTERNATIVE_NAMES VALUES(711, 74, "Lobar Atrophy Of Brain");
INSERT INTO ALTERNATIVE_NAMES VALUES(712, 74, "Lobar Atrophy of the Brain");
INSERT INTO ALTERNATIVE_NAMES VALUES(713, 74, "Pick Disease");
INSERT INTO ALTERNATIVE_NAMES VALUES(714, 74, "Pick Disease Of Brain");
INSERT INTO ALTERNATIVE_NAMES VALUES(715, 74, "Pick's Disease");
INSERT INTO ALTERNATIVE_NAMES VALUES(716, 74, "Picks Disease of Brain");

INSERT INTO CROSSREFERENCES VALUES(420, 72, "L65", 1);
INSERT INTO CROSSREFERENCES VALUES(421, 72, "146520", 4);
INSERT INTO CROSSREFERENCES VALUES(422, 72, "20448140", 3);
INSERT INTO CROSSREFERENCES VALUES(423, 73, "E85", 1);
INSERT INTO CROSSREFERENCES VALUES(424, 73, "6849372", 3);
INSERT INTO CROSSREFERENCES VALUES(425, 73, "14087279", 3);
INSERT INTO CROSSREFERENCES VALUES(426, 73, "1517901", 3);
INSERT INTO CROSSREFERENCES VALUES(427, 73, "15962837", 3);
INSERT INTO CROSSREFERENCES VALUES(428, 73, "28097620", 3);
INSERT INTO CROSSREFERENCES VALUES(429, 74, "G31", 1);
INSERT INTO CROSSREFERENCES VALUES(430, 74, "D020774", 2);
INSERT INTO CROSSREFERENCES VALUES(431, 74, "172700", 4);
INSERT INTO CROSSREFERENCES VALUES(432, 74, "30158706", 3);

INSERT INTO PROTEIN VALUES(151, "Q15517", "CDSN_HUMAN", "Corneodesmosin", "ACor", "Corneodesmosin (S protein)", 529, "CDSN", "MGSSRAPWMGRVGGHGMMALLLAGLLLPGTLAKSIGTFSDPCKDPTRITSPNDPCLTGKGDSSGFSSYSGSSSSGSSISSARSSGGGSSGSSSGSSIAQGGSAGSFKPGTGYSQVSYSSGSGSSLQGASGSSQLGSSSSHSGNSGSHSGSSSSHSSSSSSFQFSSSSFQVGNGSALPTNDNSYRGILNPSQPGQSSSSSQTSGVSSSGQSVSSNQRPCSSDIPDSPCSGGPIVSHSGPYIPSSHSVSGGQRPVVVVVDQHGSGAPGVVQGPPCSNGGLPGKPCPPITSVDKSYGGYEVVGGSSDSYLVPGMTYSKGKIYPVGYFTKENPVKGSPGVPSFAAGPPISEGKYFSSNPIIPSQSAASSAIAFQPVGTGGVQLCGGGSTGSKGPCSPSSSRVPSSSSISSSSGSPYHPCGSASQSPCSPPGTGSFSSSSSSQSSGKIILQPCGSKSSSSGHPCMSVSSLTLTGGPDGSPHPDPSAGAKPCGSSSAGKIPCRSIRDILAQVKPLGPQLADPEVFLPQGELLDSP", "Important for the epidermal barrier integrity. {ECO:0000269|PubMed:20691404}.");
INSERT INTO PROTEIN VALUES(152, "P04279", "SEMG1_HUMAN", "Semenogelin-1", "ASem1", "Semenogelin-1 (Cancer/testis antigen 103) (Semenogelin I) (SGI) [Cleaved into: Alpha-inhibin-92; Alpha-inhibin-31; Seminal basic protein]", 462, "SEMG1", "MKPNIIFVLSLLLILEKQAAVMGQKGGSKGRLPSEFSQFPHGQKGQHYSGQKGKQQTESKGSFSIQYTYHVDANDHDQSRKSQQYDLNALHKTTKSQRHLGGSQQLLHNKQEGRDHDKSKGHFHRVVIHHKGGKAHRGTQNPSQDQGNSPSGKGISSQYSNTEERLWVHGLSKEQTSVSGAQKGRKQGGSQSSYVLQTEELVANKQQRETKNSHQNKGHYQNVVEVREEHSSKVQTSLCPAHQDKLQHGSKDIFSTQDELLVYNKNQHQTKNLNQDQQHGRKANKISYQSSSTEERRLHYGENGVQKDVSQSSIYSQTEEKAQGKSQKQITIPSQEQEHSQKANKISYQSSSTEERRLHYGENGVQKDVSQRSIYSQTEKLVAGKSQIQAPNPKQEPWHGENAKGESGQSTNREQDLLSHEQKGRHQHGSHGGLDIVIIEQEDDSDRHLAQHLNNDRNPLFT", "Predominant protein in semen. It participates in the formation of a gel matrix entrapping the accessory gland secretions and ejaculated spermatozoa. Fragments of semenogelin and/or fragments of the related proteins may contribute to the activation of progressive sperm movements as the gel-forming proteins are fragmented by KLK3/PSA. {ECO:0000269|PubMed:19889947}.; Alpha-inhibin-92 and alpha-inhibin-31, derived from the proteolytic degradation of semenogelin, inhibit the secretion of pituitary follicle-stimulating hormone. {ECO:0000269|PubMed:19889947}.");


INSERT INTO PROTEIN_TO_DISEASE VALUES(785,72,151, "Major Component","", "AP00141");
INSERT INTO PROTEIN_TO_DISEASE VALUES(786,72,70, "Other Component", "20448140", "");
INSERT INTO PROTEIN_TO_DISEASE VALUES(787,73,152, "Major Component","", "AP00009");
INSERT INTO PROTEIN_TO_DISEASE VALUES(788,74,141, "Major Component","", "AP00012");

UPDATE DISEASE
SET DISEASE_ASSOCIATION = 'Chromosomal Abnormalities'
WHERE DISEASE_ID=13;
UPDATE DISEASE
SET DISEASE_TYPE = 'Clinical conditions associated with amyloidosis'
WHERE DISEASE_ID=13;

INSERT INTO DISEASE_MAPPINGS VALUES (34, 13, 1);

ALTER TABLE DISEASE CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

UPDATE DISEASE SET DISEASE_ISA_NAME = 'Aβ Amyloidosis' WHERE DISEASE_ID=1;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'AIAPP Amyloidosis' WHERE DISEASE_ID=2;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'Huntingtin Amyloidosis' WHERE DISEASE_ID=3;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'AαSyn Amyloidosis' WHERE DISEASE_ID=4;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'APrP Amyloidosis' WHERE DISEASE_ID=5;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'APrP Amyloidosis' WHERE DISEASE_ID=6;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'APrP Amyloidosis' WHERE DISEASE_ID=7;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'APro Amyloidosis' WHERE DISEASE_ID=15;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'ACal Amyloidosis' WHERE DISEASE_ID=21;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'AOAAP Amyloidosis' WHERE DISEASE_ID=35;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'APrP Amyloidosis' WHERE DISEASE_ID=36;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'AANF Amyloidosis' WHERE DISEASE_ID=37;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'AKer Amyloidosis' WHERE DISEASE_ID=38;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'APrP Amyloidosis' WHERE DISEASE_ID=39;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'ALac Amyloidosis' WHERE DISEASE_ID=43;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'AKer Amyloidosis' WHERE DISEASE_ID=44;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'APrP Amyloidosis' WHERE DISEASE_ID=67;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'ACor Amyloidosis' WHERE DISEASE_ID=72;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'ASem1 Amyloidosis' WHERE DISEASE_ID=73;
UPDATE DISEASE SET DISEASE_ISA_NAME = 'ATau Amyloidosis' WHERE DISEASE_ID=74;


INSERT INTO DISEASE VALUES(75, 'HHereditary beta-2 macroglobulin-related Amyloidosis', '', 'Amyloidosis', 'Amyloidosis', 'Spleen, Liver, Heart, Salivary Gland', 'Aβ2Mv Amyloidosis');
UPDATE DISEASE SET DISEASE_NAME = 'Hereditary beta-2 macroglobulin-related Amyloidosis' WHERE DISEASE_ID=75;
UPDATE DISEASE SET DISEASE_NAME = 'Hereditary beta-2-microglobulin-related Amyloidosis' WHERE DISEASE_ID=75;

INSERT INTO ALTERNATIVE_NAMES VALUES(717, 75, "beta2-microglobulin-related amyloidosis");
INSERT INTO ALTERNATIVE_NAMES VALUES(718, 75, "beta2-microglobulin amyloidosis");
INSERT INTO ALTERNATIVE_NAMES VALUES(719, 75, "Beta-2-microglobulin amyloidosis");
INSERT INTO ALTERNATIVE_NAMES VALUES(720, 75, "ABeta2M amyloidosis");

UPDATE ALTERNATIVE_NAMES SET DIS_ID = 75 WHERE ID=533;
UPDATE ALTERNATIVE_NAMES SET DIS_ID = 75 WHERE ID=534;
UPDATE ALTERNATIVE_NAMES SET DIS_ID = 75 WHERE ID=535;
UPDATE ALTERNATIVE_NAMES SET DIS_ID = 75 WHERE ID=536;
UPDATE ALTERNATIVE_NAMES SET DIS_ID = 75 WHERE ID=537;
UPDATE ALTERNATIVE_NAMES SET DIS_ID = 75 WHERE ID=538;

INSERT INTO CROSSREFERENCES VALUES(433, 75, "22693999", 3);
INSERT INTO CROSSREFERENCES VALUES(434, 75, "E85", 1);

UPDATE CROSSREFERENCES SET DIS_ID = 75 WHERE ID=131;
INSERT INTO PROTEIN_TO_DISEASE VALUES(789,75,128, "Major Component","", "AP00017");

UPDATE DISEASE SET DISEASE_ISA_NAME = 'Aβ2Mwt Amyloidosis' WHERE DISEASE_ID=33;
UPDATE DISEASE SET DISEASE_TISSUE = 'Musculoskeletal system' WHERE DISEASE_ID=33;
UPDATE DISEASE SET DISEASE_NAME = 'Wild type beta-2 macroglobulin-related Amyloidosis' WHERE DISEASE_ID=33;
UPDATE DISEASE SET DISEASE_NAME = 'Wild type beta-2-microglobulin-related Amyloidosis' WHERE DISEASE_ID=33;

--DELETE FROM PROTEIN WHERE PROTEIN_ID=93;
--INSERT INTO PROTEIN VALUES(93,"P10092","CALCB_HUMAN","Calcitonin gene-related peptide 2","","Calcitonin gene-related peptide 2 (Beta-type CGRP) (Beta-CGRP) (Calcitonin gene-related peptide II) (CGRP-II)",127,"CALCB","MGFRKFSPFLALSILVLYQAGSLQAAPFRSALESSPDPATLSKEDARLLLAALVQDYVQMKASELKQEQETQGSSSAAQKRACNTATCVTHRLAGLLSRSGGMVKSNFVPTNVGSKAFGRRRRDLQA","CGRP induces vasodilation. It dilates a variety of vessels including the coronary, cerebral and systemic vasculature. Its abundance in the CNS also points toward a neurotransmitter or neuromodulator role.");

UPDATE PROTEIN SET AC="P10092" WHERE PROTEIN_ID = 93;
UPDATE PROTEIN SET UNIPROT_ID="CALCB_HUMAN" WHERE PROTEIN_ID = 93;
UPDATE PROTEIN SET PRIMARY_NAME="Calcitonin gene-related peptide 2" WHERE PROTEIN_ID = 93;
UPDATE PROTEIN SET SIPE_NAME="" WHERE PROTEIN_ID = 93;
UPDATE PROTEIN SET PROTEIN_NAMES="Calcitonin gene-related peptide 2 (Beta-type CGRP) (Beta-CGRP) (Calcitonin gene-related peptide II) (CGRP-II)" WHERE PROTEIN_ID = 93;
UPDATE PROTEIN SET SEQ_LENGTH=127 WHERE PROTEIN_ID = 93;
UPDATE PROTEIN SET GENENAME="CALCB" WHERE PROTEIN_ID = 93;
UPDATE PROTEIN SET SEQUENCE="MGFRKFSPFLALSILVLYQAGSLQAAPFRSALESSPDPATLSKEDARLLLAALVQDYVQMKASELKQEQETQGSSSAAQKRACNTATCVTHRLAGLLSRSGGMVKSNFVPTNVGSKAFGRRRRDLQA" WHERE PROTEIN_ID = 93;
UPDATE PROTEIN SET FUNCTION_="CGRP induces vasodilation. It dilates a variety of vessels including the coronary, cerebral and systemic vasculature. Its abundance in the CNS also points toward a neurotransmitter or neuromodulator role." WHERE PROTEIN_ID = 93;
